<?php
// Plugin styles and scripts
function propertyowneraccess_enqueue_styles()
{
    wp_enqueue_style('property-owner-access-style', plugins_url('../assets/css/style.css', __FILE__));
    wp_enqueue_style('property-owner-access-line-awesome', 'https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css');
    wp_enqueue_style('property-owner-access-select2', 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css');
    wp_enqueue_script('property-owner-access-scripts', plugins_url('../assets/js/scripts.js', __FILE__), array('jquery'), '1.0.0', true);
    wp_enqueue_script('property-owner-access-select2', 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js', array('jquery'), '4.1.0-rc.0', true);
    wp_enqueue_script('property-owner-access-countup', plugins_url('../assets/js/countUp.min.js', __FILE__), array('jquery'), '1.0.0', true);
    wp_enqueue_script('property-owner-access-tablesort', plugins_url('../assets/js/table-sort.js', __FILE__), array('jquery'), '1.0.0', true);
    wp_enqueue_script('property-owner-access-popper', plugins_url('../assets/js/popper/popper.min.js', __FILE__), array('jquery'), '1.0.0', true);
    wp_enqueue_script('property-owner-access-tippy', plugins_url('../assets/js/tippy/tippy-bundle.umd.min.js', __FILE__), array('jquery'), '1.0.0', true);
}
add_action('wp_enqueue_scripts', 'propertyowneraccess_enqueue_styles');

// Plugin session start
function propertyowneraccess_session_start()
{
    if ( is_user_logged_in() && !session_id() ) {
        session_start();
    }
}
add_action('init', 'propertyowneraccess_session_start', 1);

// Plugin text domain
function propertyowneraccess_load_textdomain() {
    load_plugin_textdomain( 'property-owner-access', false, basename( dirname( __FILE__ ) ) . '/languages' ); 
}
add_action( 'plugins_loaded', 'propertyowneraccess_load_textdomain' );

// Custom upload mimes
function propertyowneraccess_custom_upload_mimes($mimes)
{
    $mimes['jpg'] = 'image/jpeg';
    $mimes['jpeg'] = 'image/jpeg';
    $mimes['png'] = 'image/png';
    $mimes['gif'] = 'image/gif';
    $mimes['svg'] = 'image/svg+xml';
    $mimes['doc'] = 'application/msword';
    $mimes['docx'] = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    $mimes['xls'] = 'application/vnd.ms-excel';
    $mimes['xlsx'] = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    $mimes['pdf'] = 'application/pdf';
    $mimes['zip'] = 'application/zip';
    return $mimes;
}
add_filter('upload_mimes', 'propertyowneraccess_custom_upload_mimes');

// Add the custom upload directory for the transfers
function propertyowneraccess_transfer_upload_dir($param)
{
    $param['path'] = $param['basedir'] . POA_FOLDER_TRANSFERS;
    $param['url'] = $param['baseurl'] . POA_FOLDER_TRANSFERS;
    return $param;
}

// Add the custom upload directory for the expenses
function propertyowneraccess_expense_upload_dir($param)
{
    $param['path'] = $param['basedir'] . POA_FOLDER_EXPENSES;
    $param['url'] = $param['baseurl'] . POA_FOLDER_EXPENSES;
    return $param;
}

// Add the custom upload directory for the properties
function propertyowneraccess_property_upload_dir($param)
{
    $param['path'] = $param['basedir'] . POA_FOLDER_PROPERTIES;
    $param['url'] = $param['baseurl'] . POA_FOLDER_PROPERTIES;
    return $param;
}


// Send monthly admin performance report by mail
// add_filter('cron_schedules', fn($s) => $s + ['five_minutes' => ['interval' => 300, 'display' => 'Every 5 Minutes']]);
function poa_schedule_daily_event() {
    if ( ! wp_next_scheduled( 'poa_monthly_export' ) ) {
        wp_schedule_event( time(), 'daily', 'poa_monthly_export' ); // replace with daily
    }
}
add_action( 'wp', 'poa_schedule_daily_event' );

function poa_do_daily_event() {
    // this should run only if today is the first day of the month, else return
    if (date('j') != 1) {
        return;
    }

    $firstDayLastMonth = date('Y-m-d', strtotime('first day of last month'));
    $lastDayLastMonth = date('Y-m-d', strtotime('last day of last month'));

    // Use the ExportService to generate and send the monthly export
	if (class_exists('ExportService')) {
		// Generate export for cron job (creates file + sends email)
		$exportFilePath = ExportService::generateExport(
			null, // categories (all)
			null, // apartments (all)
			$firstDayLastMonth, // checkinFrom
			$lastDayLastMonth,  // checkinTo
			false // withFilters = false (show all data for monthly report)
		);

		// Send the CSV via email when generated by cronjob
		try {
			$admin_email = get_option('admin_email');

			if (!empty($admin_email) && is_email($admin_email)) {
				$subject = 'Unhotel Performance Export - ' . date('Y-m-d H:i:s');
				$message = "Attached is the CSV export generated by the cronjob.\n\n";
				$message .= "Filters: \n";
				$message .= "Check-in: " . date('d/m/Y', strtotime($firstDayLastMonth)) . " to " . date('d/m/Y', strtotime($lastDayLastMonth)) . "\n";
				if (!empty($categories) && is_array($categories)) {
					$message .= "Categories: " . implode(', ', $categories) . "\n";
				}
				if (!empty($apartments) && is_array($apartments)) {
					$message .= "Apartments: " . implode(', ', $apartments) . "\n";
				}
				// Prepare headers
				$headers = array('From: Unhotel <info@unhotel.com.br>', 'Content-Type: text/plain; charset=UTF-8');
				// Attachments array
				$attachments = array($exportFilePath);
				// Use wp_mail to send attachment
				$mail_sent = wp_mail($admin_email, $subject, $message, $headers, $attachments);
				if (!$mail_sent) {
					error_log('[PerformancePortal] Cron export email failed to send to ' . $admin_email . ' (file: ' . $exportFilePath . ')');
				}
			}
		} catch (Exception $e) {
			error_log('[PerformancePortal] Exception while sending cron export email: ' . $e->getMessage());
		}
	}
}
add_action( 'poa_monthly_export', 'poa_do_daily_event' );

function poa_deactivate() {
    wp_clear_scheduled_hook( 'poa_monthly_export' );
}
register_deactivation_hook( __FILE__, 'poa_deactivate' );


/**
 * When we are on /poa/{lang}/page, override WPML language switcher URLs.
 */
add_filter('wpml_ls_language_url', function ($url, $language) {
    $path = trim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/');
    // Match: poa/{lang}/{rest-of-url}
    if (!preg_match('#^poa/([^/]+)/(.+)$#', $path, $m)) {
        return $url;
    }
    $rest = $m[2];
    // Get correct language code from WPML array
    $code = is_array($language) ? ($language['code'] ?? '') : (string) $language;
    if (empty($code)) {
        return $url;
    }
    return home_url('/poa/' . $code . '/' . $rest . '/');
}, 10, 2);