<?php
/**
 * @package     VikChannelManager
 * @subpackage  com_vikchannelmanager
 * @author      E4J srl
 * @copyright   Copyright (C) 2024 E4J srl. All rights reserved.
 * @license     GNU General Public License version 2 or later
 * @link        https://e4jconnect.com - https://vikwp.com
 */

// Restricted access
defined('ABSPATH') or die('No script kiddies please!');

/**
 * AI assistant generated content add-on.
 * 
 * @since 1.9.5
 */
class VCMAiAssistantAddonWritercontent extends VCMAiAssistantAddonwidget
{
    /** @var string */
    protected $content;

    /** @var string */
    protected $type;

    /**
     * Class constructor.
     * 
     * @param  string  $content  The generated text.
     * @param  string  $type     The content type (plain or html).
     */
    public function __construct(string $content, string $type)
    {
        if ($type === 'html') {
            $content = $this->sanitizeHtml($content);
        }

        $this->content = $content;
        $this->type = $type;
    }

    /**
     * @inheritDoc 
     */
    public function getTitle()
    {
        return JText::_('VBO_AITOOL_WRITER_CONTENT');
    }

    /**
     * @inheritDoc 
     */
    public function getIcon()
    {
        return VikBookingIcons::i('pen-fancy');
    }

    /**
     * @inheritDoc 
     */
    public function getSummary()
    {
        return '';
    }

    /**
     * @inheritDoc 
     */
    public function getBody()
    {
        if ($this->type === 'plain') {
            // plain text, convert new lines in <br> tags
            $content = nl2br($this->content);
        } else {
            // use HTML content as it is
            $content = $this->content;
        }

        // create body with generated content
        return '<div class="notification-wrapper"><div class="notification-message">' . $content . '</div></div>';
    }

    /**
     * @inheritDoc
     */
    public function getFooter()
    {
        $params = [
            'content' => $this->content,
            'type' => $this->type,
        ];

        // add button to notify the subscribers about the content to use
        $onClick = 'VBOCore.emitEvent(\'vbo-ai-tools-writer-content-picked\', ' . json_encode($params) . ')';
        return '<button type="button" class="btn vbo-ai-assistant-addon-btn" onclick="' . htmlspecialchars($onClick, ENT_QUOTES, 'UTF-8') . '">' . JText::_('VBO_AITOOL_WRITER_CONTENT_USE') . '</button>';
    }

    /**
     * Sanitizes the HTML generated by the AI service.
     * 
     * @param   string  $content  The provided content.
     * 
     * @return  string  The sanitized content.
     */
    protected function sanitizeHtml(string $content)
    {
        $style = '';

        // extract the <style> tag from the <head>, if specified
        if (preg_match("/<style[^>]*>(.*?)<\/style>/si", $content, $match)) {
            $style = $match[0];
        }

        // extract the body contents from the provided HTML format
        if (preg_match("/<body[^>]*>(.*?)<\/body>/si", $content, $match)) {
            $content = $match[1];
        }

        // sanitize the generated content
        $content = JComponentHelper::filterText($content);

        $uniqid = uniqid();

        // wrap the whole content within a parent div
        $content = '<div id="wrapper-' . $uniqid . '">' . trim($content) . '</div>';

        $classes = [];

        /**
         * Fetch all the tags with the "class" attribute defined.
         * Scan all the classes inside the attribute and append a unique identifier at the end of each string.
         */
        $content = preg_replace_callback("/class=[\"'](.*?)[\"']/i", function($match) use (&$classes, $uniqid) {
            // split all the classes
            $list = array_filter(preg_split("/\s+/", $match[1]));

            // join the classes to the global lookup
            $classes = array_merge($classes, $list);

            // make the classes unique to prevent conflicts with the CMS
            $list = array_map(function($class) use ($uniqid) {
                return $class . '-' . $uniqid;
            }, $list);

            // rebuild attribute with the unique classes
            return 'class="' . implode(' ', $list) . '"';
        }, $content);

        /**
         * Iterate all the classes previously manipulated and append the unique identifier also
         * to the classes defined within the <style> tag.
         */
        foreach (array_unique($classes) as $class) {
            $style = str_ireplace('.' . $class, '.' . $class . '-' . $uniqid, $style);
        }

        /**
         * Fetch all the CSS selectors defined by the <style> tag.
         * Extract each selector and make sure it refers to our custom wrapper.
         */
        $style = preg_replace_callback("/(?:^|\s)([.#a-z0-9\-_:\(\)\s,>]+)\s*{/si", function($match) use ($uniqid) {
            // split all the selectors
            $selectors = array_filter(preg_split("/\s*,\s*/", trim($match[1])));

            // make sure all the selectors refer to a parent unique wrapper
            $selectors = array_map(function($selector) use ($uniqid) {
                return '#wrapper-' . $uniqid . ' ' . $selector;
            }, $selectors);

            // join all the selectors again
            return ' ' . implode(', ', $selectors) . ' {';
        }, $style);

        return trim($style) . $content;
    }
}
