<?php
/**
 * @package     VikChannelManager
 * @subpackage  com_vikchannelmanager
 * @author      E4J srl
 * @copyright   Copyright (C) 2024 E4J srl. All rights reserved.
 * @license     GNU General Public License version 2 or later
 * @link        https://e4jconnect.com - https://vikwp.com
 */

// Restricted access
defined('ABSPATH') or die('No script kiddies please!');

/**
 * AI channel settings model.
 * 
 * @since 1.9
 * @since 1.9.12  This class doesn't extend the VCMAiModelAware any longer.
 */
class VCMAiModelSettings
{
    /**
     * The AI settings associative array.
     * 
     * @var array
     */
    protected $settings = [];

    /**
     * Class contructor.
     */
    public function __construct()
    {
        $channel = VikChannelManager::getChannel(VikChannelManagerConfig::AI);

        if ($channel) {
            $this->settings = is_string($channel['settings']) ? json_decode($channel['settings'], true) : [];
        }
    }

    /**
     * Returns true in case the channel has been configured to automatically reply to the guest messages.
     * 
     * @return  bool
     */
    public function isMessagingAutoResponderEnabled()
    {
        $enabled = $this->settings['autoresponder_messages']['value'] ?? ($this->settings['autoresponder_messages']['default'] ?? 0);

        // look for custom overrides
        return (bool) $this->alterBehavior('autoresponder_enabled', $enabled);
    }

    /**
     * Checks whether the AI should immediately reply to the guest messages or it should rather create a draft.
     * 
     * @param   int  $threshold  The minimum number of messages generated by the AI required to unlock this feature.
     * 
     * @return  bool
     */
    public function canAutoRespond(int $threshold = 20)
    {
        $db = JFactory::getDbo();

        $db->setQuery(
            $db->getQuery(true)
                ->select('COUNT(1)')
                ->from($db->qn('#__vikchannelmanager_threads_messages'))
                ->where($db->qn('sender_name') . ' = ' . $db->q('AI'))
        );

        // count the answers wrote by the AI
        $aiAnswersCount = (int) $db->loadResult();

        // we can skip the drafts in case the AI answers are higher than the specified threshold
        $skipDrafts = $aiAnswersCount >= $threshold;

        // look for custom overrides
        return (bool) $this->alterBehavior('autoresponder_skip_drafts', $skipDrafts, [
            'threshold' => $threshold,
            'answers' => $aiAnswersCount,
        ]);
    }

    /**
     * Returns the signature of the AI, which will be added to the end of the message whenever the latter automatically replies.
     * 
     * @return  string
     */
    public function getMessagingSignature()
    {
        $signature = $this->settings['autoresponder_messages_footer']['value'] ?? ($this->settings['autoresponder_messages_footer']['default'] ?? '');

        // look for custom overrides
        return (string) $this->alterBehavior('autoresponder_signature', $signature);
    }

    /**
     * Returns true in case the channel has been configured to automatically reply to the reviews left by the guests.
     * 
     * @return  bool
     */
    public function isReviewReplyAutoResponderEnabled()
    {
        $enabled = $this->settings['autoresponder_review_reply']['value'] ?? ($this->settings['autoresponder_review_reply']['default'] ?? 0);

        // look for custom overrides
        return (bool) $this->alterBehavior('autoresponder_review_reply', $enabled);
    }

    /**
     * Checks whether the review should ignore the auto-reply to a review because its score is too low.
     * 
     * @param   int   $score  The review overall score.
     * 
     * @return  bool
     */
    public function shouldExcludeNegativeReview(int $score)
    {
        $ignoreNegativeReview = (bool) ($this->settings['ignore_negative_reviews']['value'] ?? ($this->settings['ignore_negative_reviews']['default'] ?? 0));

        // we should exclude the auto-review in case the score is not sufficient (lower than 6)
        $shouldExclude = $ignoreNegativeReview && $score < 6;

        // look for custom overrides
        return (bool) $this->alterBehavior('exclude_negative_review', $shouldExclude, [
            'score' => $score,
        ]);
    }

    /**
     * Returns true in case the channel has been configured to automatically review the guests 3 days after the check-out.
     * 
     * @return  bool
     */
    public function isGuestReviewAutoResponderEnabled()
    {
        $enabled = $this->settings['autoresponder_review_guest']['value'] ?? ($this->settings['autoresponder_review_guest']['default'] ?? 0);

        // look for custom overrides
        return (bool) $this->alterBehavior('autoresponder_review_guest', $enabled);
    }

    /**
     * Triggers an action to let third-party plugins override the configured setting at runtime.
     * 
     * @param   string  $settingName   The name of the setting.
     * @param   mixed   $settingValue  The configured value of the setting.
     * @param   array   $args          An associative array of extra arguments.
     * 
     * @return  mixed   The resulting value.
     * 
     * @since   1.9.16
     */
    protected function alterBehavior(string $settingName, $settingValue, array $args = [])
    {
        /**
         * Third-party plugins can update the `$settingValue` argument by reference to alter
         * the behavior of the configured setting at runtime.
         * 
         * @param   string  $settingName    The name of the setting.
         * @param   mixed   &$settingValue  The configured value of the setting.
         * @param   array   $args           An associative array of extra arguments.
         * 
         * @since   1.9.16
         */
        VCMFactory::getPlatform()->getDispatcher()->trigger(
            'onAlterSettingsModelAI',
            [
                $settingName,
                &$settingValue,
                $args,
            ]
        );

        return $settingValue;
    }
}
