<?php
/**
 * @package     VikChannelManager
 * @subpackage  com_vikchannelmanager
 * @author      e4j - Extensionsforjoomla.com
 * @copyright   Copyright (C) 2018 e4j - Extensionsforjoomla.com. All rights reserved.
 * @license     GNU General Public License version 2 or later
 * @link        https://e4jconnect.com - https://vikwp.com
 */

// No direct access to this file
defined('ABSPATH') or die('No script kiddies please!');

// import Joomla view library
jimport('joomla.application.component.view');

class VikChannelManagerViewbcahcont extends JViewUI {
	
	function display($tpl = null) {
		// Set the toolbar
		$this->addToolBar();
		
		VCM::load_css_js();
		VCM::load_complex_select();
		
		$dbo = JFactory::getDbo();
	
		$config = VikChannelManager::loadConfiguration();
		
		$this->config = $config;

		$oldData = new stdClass();

		$module = VikChannelManager::getActiveModule(true);

		$channel = VikChannelManager::getActiveModule(true);
		$channel['params'] = json_decode($channel['params'], true);

		$inputTypeReset = VikRequest::getInt('insertTypeReSet');


		$hotelName="";

		if($module['av_enabled'] == 1) {
			//this query below is safe with the error #1055 when sql_mode=only_full_group_by for the aggregate functions
			$q = "SELECT `prop_name`,`prop_params`, COUNT(DISTINCT `idroomota`) AS `tot_rooms` FROM `#__vikchannelmanager_roomsxref` WHERE `idchannel`=".(int)$module['uniquekey']." GROUP BY `prop_name`,`prop_params` ORDER BY `prop_name` ASC;";
			$dbo->setQuery($q);
			$dbo->execute();
			if( $dbo->getNumRows() > 0 ) {
				$other_accounts = $dbo->loadAssocList();
				foreach ($other_accounts as $oacc) {
					if(!empty($oacc['prop_params'])) {
						$hotelID = json_decode($oacc['prop_params'],true)['hotelid'];
						if($hotelID==$channel['params']['hotelid']){
							$hotelName = $oacc['prop_name'];
						}
					}
				}
			}
		}

		$q = "SELECT `setting` FROM `#__vikchannelmanager_config` WHERE `param`='bcahcont".$channel['params']['hotelid']."';";
		$dbo->setQuery($q);
		$dbo->execute();
		//echo "<pre>".print_r($_REQUEST, true)."</pre>";die;
		if ($dbo->getNumRows() > 0) {
			$oldData = $dbo->loadAssoc();
			//echo "<pre>".print_r($oldData,true)."</pre>";
			$oldData=json_decode($oldData['setting']);
			/*echo "<pre>".print_r($oldData,true)."</pre>";
			echo "<pre>".print_r($oldData->people,true)."</pre>";*/
			if(!empty($oldData)){
				//echo "<pre>".print_r($oldData,true)."</pre>";
			}
			else{
				$oldData = new stdClass();
			}
		}

		$session = JFactory::getSession();
		$sessionValues = null;
		if ($session->has('vcmbcahcont'.$channel['params']['hotelid'])) {
			$sessionValues = json_decode($session->get('vcmbcahcont'.$channel['params']['hotelid']));
		}

		$RMAAmenitiesNames = array(
			JText::_('VCMBCAHAMENTYPE2'),
			JText::_('VCMBCAHAMENTYPE3'),
			JText::_('VCMBCAHAMENTYPE4'),
			JText::_('VCMBCAHAMENTYPE5'),
			JText::_('VCMBCAHAMENTYPE6'),
			JText::_('VCMBCAHAMENTYPE7'),
			JText::_('VCMBCAHAMENTYPE8'),
			JText::_('VCMBCAHAMENTYPE9'),
			JText::_('VCMBCAHAMENTYPE10'),
			JText::_('VCMBCAHAMENTYPE11'),
			JText::_('VCMBCAHAMENTYPE12'),
			JText::_('VCMBCAHAMENTYPE13'),
			JText::_('VCMBCAHAMENTYPE14'),
			JText::_('VCMBCAHAMENTYPE15'),
			JText::_('VCMBCAHAMENTYPE16'),
			JText::_('VCMBCAHAMENTYPE17'),
			JText::_('VCMBCAHAMENTYPE18'),
			JText::_('VCMBCAHAMENTYPE19'),
			JText::_('VCMBCAHAMENTYPE20'),
			JText::_('VCMBCAHAMENTYPE21'),
			JText::_('VCMBCAHAMENTYPE22'),
			JText::_('VCMBCAHAMENTYPE23'),
			JText::_('VCMBCAHAMENTYPE24'),
			JText::_('VCMBCAHAMENTYPE25'),
			JText::_('VCMBCAHAMENTYPE26'),
			JText::_('VCMBCAHAMENTYPE27'),
			JText::_('VCMBCAHAMENTYPE28'),
			JText::_('VCMBCAHAMENTYPE29'),
			JText::_('VCMBCAHAMENTYPE30'),
			JText::_('VCMBCAHAMENTYPE31'),
			JText::_('VCMBCAHAMENTYPE32'),
			JText::_('VCMBCAHAMENTYPE33'),
			JText::_('VCMBCAHAMENTYPE34'),
			JText::_('VCMBCAHAMENTYPE35'),
			JText::_('VCMBCAHAMENTYPE36'),
			JText::_('VCMBCAHAMENTYPE37'),
			JText::_('VCMBCAHAMENTYPE38'),
			JText::_('VCMBCAHAMENTYPE39'),
			JText::_('VCMBCAHAMENTYPE40'),
			JText::_('VCMBCAHAMENTYPE41'),
			JText::_('VCMBCAHAMENTYPE42'),
			JText::_('VCMBCAHAMENTYPE43'),
			JText::_('VCMBCAHAMENTYPE44'),
			JText::_('VCMBCAHAMENTYPE45'),
			JText::_('VCMBCAHAMENTYPE46'),
			JText::_('VCMBCAHAMENTYPE47'),
			JText::_('VCMBCAHAMENTYPE48'),
			JText::_('VCMBCAHAMENTYPE49'),
			JText::_('VCMBCAHAMENTYPE50'),
			JText::_('VCMBCAHAMENTYPE51'),
			JText::_('VCMBCAHAMENTYPE52'),
			JText::_('VCMBCAHAMENTYPE53'),
			JText::_('VCMBCAHAMENTYPE54'),
			JText::_('VCMBCAHAMENTYPE55'),
			JText::_('VCMBCAHAMENTYPE56'),
			JText::_('VCMBCAHAMENTYPE57'),
			JText::_('VCMBCAHAMENTYPE58'),
			JText::_('VCMBCAHAMENTYPE59'),
			JText::_('VCMBCAHAMENTYPE60'),
			JText::_('VCMBCAHAMENTYPE61'),
			JText::_('VCMBCAHAMENTYPE62'),
			JText::_('VCMBCAHAMENTYPE63'),
			JText::_('VCMBCAHAMENTYPE64'),
			JText::_('VCMBCAHAMENTYPE65'),
			JText::_('VCMBCAHAMENTYPE66'),
			JText::_('VCMBCAHAMENTYPE67'),
			JText::_('VCMBCAHAMENTYPE68'),
			JText::_('VCMBCAHAMENTYPE69'),
			JText::_('VCMBCAHAMENTYPE70'),
			JText::_('VCMBCAHAMENTYPE71'),
			JText::_('VCMBCAHAMENTYPE72'),
			JText::_('VCMBCAHAMENTYPE73'),
			JText::_('VCMBCAHAMENTYPE74'),
			JText::_('VCMBCAHAMENTYPE75'),
			JText::_('VCMBCAHAMENTYPE76'),
			JText::_('VCMBCAHAMENTYPE77'),
			JText::_('VCMBCAHAMENTYPE78'),
			JText::_('VCMBCAHAMENTYPE79'),
			JText::_('VCMBCAHAMENTYPE80'),
			JText::_('VCMBCAHAMENTYPE81'),
			JText::_('VCMBCAHAMENTYPE82'),
			JText::_('VCMBCAHAMENTYPE83'),
			JText::_('VCMBCAHAMENTYPE84'),
			JText::_('VCMBCAHAMENTYPE85'),
			JText::_('VCMBCAHAMENTYPE86'),
			JText::_('VCMBCAHAMENTYPE87'),
			JText::_('VCMBCAHAMENTYPE88'),
			JText::_('VCMBCAHAMENTYPE89'),
			JText::_('VCMBCAHAMENTYPE90'),
			JText::_('VCMBCAHAMENTYPE91'),
			JText::_('VCMBCAHAMENTYPE92'),
			JText::_('VCMBCAHAMENTYPE93'),
			JText::_('VCMBCAHAMENTYPE94'),
			JText::_('VCMBCAHAMENTYPE95'),
			JText::_('VCMBCAHAMENTYPE96'),
			JText::_('VCMBCAHAMENTYPE97'),
			JText::_('VCMBCAHAMENTYPE98'),
			JText::_('VCMBCAHAMENTYPE99'),
			JText::_('VCMBCAHAMENTYPE100'),
			JText::_('VCMBCAHAMENTYPE101'),
			JText::_('VCMBCAHAMENTYPE102'),
			JText::_('VCMBCAHAMENTYPE103'),
			JText::_('VCMBCAHAMENTYPE104'),
			JText::_('VCMBCAHAMENTYPE105'),
			JText::_('VCMBCAHAMENTYPE106'),
			JText::_('VCMBCAHAMENTYPE107'),
			JText::_('VCMBCAHAMENTYPE108'),
			JText::_('VCMBCAHAMENTYPE109'),
			JText::_('VCMBCAHAMENTYPE110'),
			JText::_('VCMBCAHAMENTYPE111'),
			JText::_('VCMBCAHAMENTYPE112'),
			JText::_('VCMBCAHAMENTYPE113'),
			JText::_('VCMBCAHAMENTYPE114'),
			JText::_('VCMBCAHAMENTYPE115'),
			JText::_('VCMBCAHAMENTYPE116'),
			JText::_('VCMBCAHAMENTYPE117'),
			JText::_('VCMBCAHAMENTYPE118'),
			JText::_('VCMBCAHAMENTYPE119'),
			JText::_('VCMBCAHAMENTYPE120'),
			JText::_('VCMBCAHAMENTYPE121'),
			JText::_('VCMBCAHAMENTYPE122'),
			JText::_('VCMBCAHAMENTYPE123'),
			JText::_('VCMBCAHAMENTYPE124'),
			JText::_('VCMBCAHAMENTYPE125'),
			JText::_('VCMBCAHAMENTYPE126'),
			JText::_('VCMBCAHAMENTYPE127'),
			JText::_('VCMBCAHAMENTYPE128'),
			JText::_('VCMBCAHAMENTYPE129'),
			JText::_('VCMBCAHAMENTYPE130'),
			JText::_('VCMBCAHAMENTYPE131'),
			JText::_('VCMBCAHAMENTYPE132'),
			JText::_('VCMBCAHAMENTYPE133'),
			JText::_('VCMBCAHAMENTYPE134'),
			JText::_('VCMBCAHAMENTYPE135'),
			JText::_('VCMBCAHAMENTYPE136'),
			JText::_('VCMBCAHAMENTYPE137'),
			JText::_('VCMBCAHAMENTYPE138'),
			JText::_('VCMBCAHAMENTYPE139'),
			JText::_('VCMBCAHAMENTYPE140'),
			JText::_('VCMBCAHAMENTYPE141'),
			JText::_('VCMBCAHAMENTYPE142'),
			JText::_('VCMBCAHAMENTYPE143'),
			JText::_('VCMBCAHAMENTYPE144'),
			JText::_('VCMBCAHAMENTYPE145'),
			JText::_('VCMBCAHAMENTYPE146'),
			JText::_('VCMBCAHAMENTYPE147'),
			JText::_('VCMBCAHAMENTYPE148'),
			JText::_('VCMBCAHAMENTYPE149'),
			JText::_('VCMBCAHAMENTYPE150'),
			JText::_('VCMBCAHAMENTYPE151'),
			JText::_('VCMBCAHAMENTYPE152'),
			JText::_('VCMBCAHAMENTYPE153'),
			JText::_('VCMBCAHAMENTYPE154'),
			JText::_('VCMBCAHAMENTYPE155'),
			JText::_('VCMBCAHAMENTYPE156'),
			JText::_('VCMBCAHAMENTYPE157'),
			JText::_('VCMBCAHAMENTYPE158'),
			JText::_('VCMBCAHAMENTYPE159'),
			JText::_('VCMBCAHAMENTYPE160'),
			JText::_('VCMBCAHAMENTYPE161'),
			JText::_('VCMBCAHAMENTYPE162')
		);

		$RMAAmenitiesCodes = array(
			JText::_('VCMBCAHAMENTYPE2') => 2,
			JText::_('VCMBCAHAMENTYPE3') => 3,
			JText::_('VCMBCAHAMENTYPE4') => 5,
			JText::_('VCMBCAHAMENTYPE5') => 8,
			JText::_('VCMBCAHAMENTYPE6') => 9,
			JText::_('VCMBCAHAMENTYPE7') => 10,
			JText::_('VCMBCAHAMENTYPE8') => 11,
			JText::_('VCMBCAHAMENTYPE9') => 13,
			JText::_('VCMBCAHAMENTYPE10') => 14,
			JText::_('VCMBCAHAMENTYPE11') => 16,
			JText::_('VCMBCAHAMENTYPE12') => 18,
			JText::_('VCMBCAHAMENTYPE13') => 19,
			JText::_('VCMBCAHAMENTYPE14') => 20,
			JText::_('VCMBCAHAMENTYPE15') => 21,
			JText::_('VCMBCAHAMENTYPE16') => 22,
			JText::_('VCMBCAHAMENTYPE17') => 25,
			JText::_('VCMBCAHAMENTYPE18') => 26,
			JText::_('VCMBCAHAMENTYPE19') => 28,
			JText::_('VCMBCAHAMENTYPE20') => 29,
			JText::_('VCMBCAHAMENTYPE21') => 32,
			JText::_('VCMBCAHAMENTYPE22') => 33,
			JText::_('VCMBCAHAMENTYPE23') => 38,
			JText::_('VCMBCAHAMENTYPE24') => 41,
			JText::_('VCMBCAHAMENTYPE25') => 46,
			JText::_('VCMBCAHAMENTYPE26') => 47,
			JText::_('VCMBCAHAMENTYPE27') => 49,
			JText::_('VCMBCAHAMENTYPE28') => 50,
			JText::_('VCMBCAHAMENTYPE29') => 54,
			JText::_('VCMBCAHAMENTYPE30') => 55,
			JText::_('VCMBCAHAMENTYPE31') => 56,
			JText::_('VCMBCAHAMENTYPE32') => 57,
			JText::_('VCMBCAHAMENTYPE33') => 58,
			JText::_('VCMBCAHAMENTYPE34') => 59,
			JText::_('VCMBCAHAMENTYPE35') => 60,
			JText::_('VCMBCAHAMENTYPE36') => 61,
			JText::_('VCMBCAHAMENTYPE37') => 63,
			JText::_('VCMBCAHAMENTYPE38') => 64,
			JText::_('VCMBCAHAMENTYPE39') => 68,
			JText::_('VCMBCAHAMENTYPE40') => 69,
			JText::_('VCMBCAHAMENTYPE41') => 72,
			JText::_('VCMBCAHAMENTYPE42') => 77,
			JText::_('VCMBCAHAMENTYPE43') => 78,
			JText::_('VCMBCAHAMENTYPE44') => 80,
			JText::_('VCMBCAHAMENTYPE45') => 81,
			JText::_('VCMBCAHAMENTYPE46') => 85,
			JText::_('VCMBCAHAMENTYPE47') => 86,
			JText::_('VCMBCAHAMENTYPE48') => 88,
			JText::_('VCMBCAHAMENTYPE49') => 89,
			JText::_('VCMBCAHAMENTYPE50') => 91,
			JText::_('VCMBCAHAMENTYPE51') => 92,
			JText::_('VCMBCAHAMENTYPE52') => 94,
			JText::_('VCMBCAHAMENTYPE53') => 97,
			JText::_('VCMBCAHAMENTYPE54') => 98,
			JText::_('VCMBCAHAMENTYPE55') => 99,
			JText::_('VCMBCAHAMENTYPE56') => 103,
			JText::_('VCMBCAHAMENTYPE57') => 105,
			JText::_('VCMBCAHAMENTYPE58') => 108,
			JText::_('VCMBCAHAMENTYPE59') => 113,
			JText::_('VCMBCAHAMENTYPE60') => 115,
			JText::_('VCMBCAHAMENTYPE61') => 117,
			JText::_('VCMBCAHAMENTYPE62') => 119,
			JText::_('VCMBCAHAMENTYPE63') => 123,
			JText::_('VCMBCAHAMENTYPE64') => 126,
			JText::_('VCMBCAHAMENTYPE65') => 127,
			JText::_('VCMBCAHAMENTYPE66') => 129,
			JText::_('VCMBCAHAMENTYPE67') => 133,
			JText::_('VCMBCAHAMENTYPE68') => 138,
			JText::_('VCMBCAHAMENTYPE69') => 139,
			JText::_('VCMBCAHAMENTYPE70') => 141,
			JText::_('VCMBCAHAMENTYPE71') => 142,
			JText::_('VCMBCAHAMENTYPE72') => 144,
			JText::_('VCMBCAHAMENTYPE73') => 146,
			JText::_('VCMBCAHAMENTYPE74') => 147,
			JText::_('VCMBCAHAMENTYPE75') => 149,
			JText::_('VCMBCAHAMENTYPE76') => 155,
			JText::_('VCMBCAHAMENTYPE77') => 157,
			JText::_('VCMBCAHAMENTYPE78') => 158,
			JText::_('VCMBCAHAMENTYPE79') => 162,
			JText::_('VCMBCAHAMENTYPE80') => 163,
			JText::_('VCMBCAHAMENTYPE81') => 164,
			JText::_('VCMBCAHAMENTYPE82') => 166,
			JText::_('VCMBCAHAMENTYPE83') => 167,
			JText::_('VCMBCAHAMENTYPE84') => 193,
			JText::_('VCMBCAHAMENTYPE85') => 194,
			JText::_('VCMBCAHAMENTYPE86') => 200,
			JText::_('VCMBCAHAMENTYPE87') => 203,
			JText::_('VCMBCAHAMENTYPE88') => 210,
			JText::_('VCMBCAHAMENTYPE89') => 214,
			JText::_('VCMBCAHAMENTYPE90') => 217,
			JText::_('VCMBCAHAMENTYPE91') => 218,
			JText::_('VCMBCAHAMENTYPE92') => 220,
			JText::_('VCMBCAHAMENTYPE93') => 223,
			JText::_('VCMBCAHAMENTYPE94') => 224,
			JText::_('VCMBCAHAMENTYPE95') => 228,
			JText::_('VCMBCAHAMENTYPE96') => 230,
			JText::_('VCMBCAHAMENTYPE97') => 234,
			JText::_('VCMBCAHAMENTYPE98') => 245,
			JText::_('VCMBCAHAMENTYPE99') => 246,
			JText::_('VCMBCAHAMENTYPE100') => 249,
			JText::_('VCMBCAHAMENTYPE101') => 251,
			JText::_('VCMBCAHAMENTYPE102') => 254,
			JText::_('VCMBCAHAMENTYPE103') => 256,
			JText::_('VCMBCAHAMENTYPE104') => 258,
			JText::_('VCMBCAHAMENTYPE105') => 259,
			JText::_('VCMBCAHAMENTYPE106') => 260,
			JText::_('VCMBCAHAMENTYPE107') => 262,
			JText::_('VCMBCAHAMENTYPE108') => 265,
			JText::_('VCMBCAHAMENTYPE109') => 268,
			JText::_('VCMBCAHAMENTYPE110') => 270,
			JText::_('VCMBCAHAMENTYPE111') => 271,
			JText::_('VCMBCAHAMENTYPE112') => 273,
			JText::_('VCMBCAHAMENTYPE113') => 276,
			JText::_('VCMBCAHAMENTYPE114') => 5001,
			JText::_('VCMBCAHAMENTYPE115') => 5013,
			JText::_('VCMBCAHAMENTYPE116') => 5015,
			JText::_('VCMBCAHAMENTYPE117') => 5017,
			JText::_('VCMBCAHAMENTYPE118') => 5034,
			JText::_('VCMBCAHAMENTYPE119') => 5037,
			JText::_('VCMBCAHAMENTYPE120') => 5039,
			JText::_('VCMBCAHAMENTYPE121') => 5041,
			JText::_('VCMBCAHAMENTYPE122') => 5042,
			JText::_('VCMBCAHAMENTYPE123') => 5070,
			JText::_('VCMBCAHAMENTYPE124') => 5072,
			JText::_('VCMBCAHAMENTYPE125') => 5076,
			JText::_('VCMBCAHAMENTYPE126') => 5077,
			JText::_('VCMBCAHAMENTYPE127') => 5080,
			JText::_('VCMBCAHAMENTYPE128') => 5081,
			JText::_('VCMBCAHAMENTYPE129') => 5082,
			JText::_('VCMBCAHAMENTYPE130') => 5086,
			JText::_('VCMBCAHAMENTYPE131') => 5087,
			JText::_('VCMBCAHAMENTYPE132') => 5090,
			JText::_('VCMBCAHAMENTYPE133') => 5091,
			JText::_('VCMBCAHAMENTYPE134') => 5092,
			JText::_('VCMBCAHAMENTYPE135') => 5102,
			JText::_('VCMBCAHAMENTYPE136') => 5104,
			JText::_('VCMBCAHAMENTYPE137') => 5105,
			JText::_('VCMBCAHAMENTYPE138') => 5106,
			JText::_('VCMBCAHAMENTYPE139') => 5107,
			JText::_('VCMBCAHAMENTYPE140') => 5109,
			JText::_('VCMBCAHAMENTYPE141') => 5110,
			JText::_('VCMBCAHAMENTYPE142') => 5111,
			JText::_('VCMBCAHAMENTYPE143') => 5113,
			JText::_('VCMBCAHAMENTYPE144') => 5116,
			JText::_('VCMBCAHAMENTYPE145') => 5117,
			JText::_('VCMBCAHAMENTYPE146') => 5118,
			JText::_('VCMBCAHAMENTYPE147') => 5121,
			JText::_('VCMBCAHAMENTYPE148') => 5122,
			JText::_('VCMBCAHAMENTYPE149') => 5124,
			JText::_('VCMBCAHAMENTYPE150') => 5126,
			JText::_('VCMBCAHAMENTYPE151') => 5127,
			JText::_('VCMBCAHAMENTYPE152') => 5129,
			JText::_('VCMBCAHAMENTYPE153') => 5130,
			JText::_('VCMBCAHAMENTYPE154') => 5131,
			JText::_('VCMBCAHAMENTYPE155') => 5132,
			JText::_('VCMBCAHAMENTYPE156') => 5133,
			JText::_('VCMBCAHAMENTYPE157') => 5134,
			JText::_('VCMBCAHAMENTYPE158') => 5135,
			JText::_('VCMBCAHAMENTYPE159') => 5136,
			JText::_('VCMBCAHAMENTYPE160') => 5137,
			JText::_('VCMBCAHAMENTYPE161') => 5138,
			JText::_('VCMBCAHAMENTYPE162') => 5146
		);
		
		$languageCodes = array(
			JText::_('VCMBCAHLANG1') => "ar",
			JText::_('VCMBCAHLANG2') => "az",
			JText::_('VCMBCAHLANG3') => "bg",
			JText::_('VCMBCAHLANG4') => "ca",
			JText::_('VCMBCAHLANG5') => "cs",
			JText::_('VCMBCAHLANG6') => "da",
			JText::_('VCMBCAHLANG7') => "de",
			JText::_('VCMBCAHLANG8') => "el",
			JText::_('VCMBCAHLANG9') => "en",
			JText::_('VCMBCAHLANG10') => "es",
			JText::_('VCMBCAHLANG11') => "et",
			JText::_('VCMBCAHLANG12') => "fr",
			JText::_('VCMBCAHLANG13') => "fi",
			JText::_('VCMBCAHLANG14') => "he",
			JText::_('VCMBCAHLANG15') => "hi",
			JText::_('VCMBCAHLANG16') => "hr",
			JText::_('VCMBCAHLANG17') => "hu",
			JText::_('VCMBCAHLANG18') => "id",
			JText::_('VCMBCAHLANG19') => "is",
			JText::_('VCMBCAHLANG20') => "it",
			JText::_('VCMBCAHLANG21') => "ja",
			JText::_('VCMBCAHLANG22') => "km",
			JText::_('VCMBCAHLANG23') => "ko",
			JText::_('VCMBCAHLANG24') => "lo",
			JText::_('VCMBCAHLANG25') => "lt",
			JText::_('VCMBCAHLANG26') => "lv",
			JText::_('VCMBCAHLANG27') => "ms",
			JText::_('VCMBCAHLANG28') => "nl",
			JText::_('VCMBCAHLANG29') => "no",
			JText::_('VCMBCAHLANG30') => "pl",
			JText::_('VCMBCAHLANG31') => "pt",
			JText::_('VCMBCAHLANG32') => "ro",
			JText::_('VCMBCAHLANG33') => "ru",
			JText::_('VCMBCAHLANG34') => "sk",
			JText::_('VCMBCAHLANG35') => "sl",
			JText::_('VCMBCAHLANG36') => "sr",
			JText::_('VCMBCAHLANG37') => "sv",
			JText::_('VCMBCAHLANG38') => "tl",
			JText::_('VCMBCAHLANG39') => "th",
			JText::_('VCMBCAHLANG40') => "tr",
			JText::_('VCMBCAHLANG41') => "uk",
			JText::_('VCMBCAHLANG42') => "vi",
			JText::_('VCMBCAHLANG43') => "xb",
			JText::_('VCMBCAHLANG44') => "xs",
			JText::_('VCMBCAHLANG45') => "xt",
			JText::_('VCMBCAHLANG46') => "xu",
			JText::_('VCMBCAHLANG47') => "zh"
		);

		$countryCodes = array(
			JText::_('VCMBCAHNATION1') => "AF",
			JText::_('VCMBCAHNATION2') => "AX",
			JText::_('VCMBCAHNATION3') => "AL",
			JText::_('VCMBCAHNATION4') => "DZ",
			JText::_('VCMBCAHNATION5') => "AS",
			JText::_('VCMBCAHNATION6') => "AD",
			JText::_('VCMBCAHNATION7') => "AO",
			JText::_('VCMBCAHNATION8') => "AI",
			JText::_('VCMBCAHNATION9') => "AQ",
			JText::_('VCMBCAHNATION10') => "AG",
			JText::_('VCMBCAHNATION11') => "AR",
			JText::_('VCMBCAHNATION12') => "AM",
			JText::_('VCMBCAHNATION13') => "AW",
			JText::_('VCMBCAHNATION14') => "AU",
			JText::_('VCMBCAHNATION15') => "AT",
			JText::_('VCMBCAHNATION16') => "AZ",
			JText::_('VCMBCAHNATION17') => "BS",
			JText::_('VCMBCAHNATION18') => "BH",
			JText::_('VCMBCAHNATION19') => "BD",
			JText::_('VCMBCAHNATION20') => "BB",
			JText::_('VCMBCAHNATION21') => "BY",
			JText::_('VCMBCAHNATION22') => "BE",
			JText::_('VCMBCAHNATION23') => "BZ",
			JText::_('VCMBCAHNATION24') => "BJ",
			JText::_('VCMBCAHNATION25') => "BM",
			JText::_('VCMBCAHNATION26') => "BT",
			JText::_('VCMBCAHNATION27') => "BO",
			JText::_('VCMBCAHNATION28') => "BQ",
			JText::_('VCMBCAHNATION29') => "BA",
			JText::_('VCMBCAHNATION30') => "BW",
			JText::_('VCMBCAHNATION31') => "BV",
			JText::_('VCMBCAHNATION32') => "BR",
			JText::_('VCMBCAHNATION33') => "IO",
			JText::_('VCMBCAHNATION34') => "BN",
			JText::_('VCMBCAHNATION35') => "BG",
			JText::_('VCMBCAHNATION36') => "BF",
			JText::_('VCMBCAHNATION37') => "BI",
			JText::_('VCMBCAHNATION38') => "KH",
			JText::_('VCMBCAHNATION39') => "CM",
			JText::_('VCMBCAHNATION40') => "CA",
			JText::_('VCMBCAHNATION41') => "CV",
			JText::_('VCMBCAHNATION42') => "KY",
			JText::_('VCMBCAHNATION43') => "CF",
			JText::_('VCMBCAHNATION44') => "TD",
			JText::_('VCMBCAHNATION45') => "CL",
			JText::_('VCMBCAHNATION46') => "CN",
			JText::_('VCMBCAHNATION47') => "CX",
			JText::_('VCMBCAHNATION48') => "CC",
			JText::_('VCMBCAHNATION49') => "CO",
			JText::_('VCMBCAHNATION50') => "KM",
			JText::_('VCMBCAHNATION51') => "CG",
			JText::_('VCMBCAHNATION52') => "CD",
			JText::_('VCMBCAHNATION53') => "CK",
			JText::_('VCMBCAHNATION54') => "CR",
			JText::_('VCMBCAHNATION55') => "CI",
			JText::_('VCMBCAHNATION56') => "HR",
			JText::_('VCMBCAHNATION57') => "CU",
			JText::_('VCMBCAHNATION58') => "CW",
			JText::_('VCMBCAHNATION59') => "CY",
			JText::_('VCMBCAHNATION60') => "CZ",
			JText::_('VCMBCAHNATION61') => "DK",
			JText::_('VCMBCAHNATION62') => "DJ",
			JText::_('VCMBCAHNATION63') => "DM",
			JText::_('VCMBCAHNATION64') => "DO",
			JText::_('VCMBCAHNATION65') => "EC",
			JText::_('VCMBCAHNATION66') => "EG",
			JText::_('VCMBCAHNATION67') => "SV",
			JText::_('VCMBCAHNATION68') => "GQ",
			JText::_('VCMBCAHNATION69') => "ER",
			JText::_('VCMBCAHNATION70') => "EE",
			JText::_('VCMBCAHNATION71') => "ET",
			JText::_('VCMBCAHNATION72') => "FK",
			JText::_('VCMBCAHNATION73') => "FO",
			JText::_('VCMBCAHNATION74') => "FJ",
			JText::_('VCMBCAHNATION75') => "FI",
			JText::_('VCMBCAHNATION76') => "FR",
			JText::_('VCMBCAHNATION77') => "GF",
			JText::_('VCMBCAHNATION78') => "PF",
			JText::_('VCMBCAHNATION79') => "TF",
			JText::_('VCMBCAHNATION80') => "GA",
			JText::_('VCMBCAHNATION81') => "GM",
			JText::_('VCMBCAHNATION82') => "GE",
			JText::_('VCMBCAHNATION83') => "DE",
			JText::_('VCMBCAHNATION84') => "GH",
			JText::_('VCMBCAHNATION85') => "GI",
			JText::_('VCMBCAHNATION86') => "GR",
			JText::_('VCMBCAHNATION87') => "GL",
			JText::_('VCMBCAHNATION88') => "GD",
			JText::_('VCMBCAHNATION89') => "GP",
			JText::_('VCMBCAHNATION90') => "GU",
			JText::_('VCMBCAHNATION91') => "GT",
			JText::_('VCMBCAHNATION92') => "GG",
			JText::_('VCMBCAHNATION93') => "GN",
			JText::_('VCMBCAHNATION94') => "GW",
			JText::_('VCMBCAHNATION95') => "GY",
			JText::_('VCMBCAHNATION96') => "HT",
			JText::_('VCMBCAHNATION97') => "HM",
			JText::_('VCMBCAHNATION98') => "VA",
			JText::_('VCMBCAHNATION99') => "HN",
			JText::_('VCMBCAHNATION100') => "HK",
			JText::_('VCMBCAHNATION101') => "HU",
			JText::_('VCMBCAHNATION102') => "IS",
			JText::_('VCMBCAHNATION103') => "IN",
			JText::_('VCMBCAHNATION104') => "ID",
			JText::_('VCMBCAHNATION105') => "IR",
			JText::_('VCMBCAHNATION106') => "IQ",
			JText::_('VCMBCAHNATION107') => "IE",
			JText::_('VCMBCAHNATION108') => "IM",
			JText::_('VCMBCAHNATION109') => "IL",
			JText::_('VCMBCAHNATION110') => "IT",
			JText::_('VCMBCAHNATION111') => "JM",
			JText::_('VCMBCAHNATION112') => "JP",
			JText::_('VCMBCAHNATION113') => "JE",
			JText::_('VCMBCAHNATION114') => "JO",
			JText::_('VCMBCAHNATION115') => "KZ",
			JText::_('VCMBCAHNATION116') => "KE",
			JText::_('VCMBCAHNATION117') => "KI",
			JText::_('VCMBCAHNATION118') => "KP",
			JText::_('VCMBCAHNATION119') => "KR",
			JText::_('VCMBCAHNATION120') => "KW",
			JText::_('VCMBCAHNATION121') => "KG",
			JText::_('VCMBCAHNATION122') => "LA",
			JText::_('VCMBCAHNATION123') => "LV",
			JText::_('VCMBCAHNATION124') => "LB",
			JText::_('VCMBCAHNATION125') => "LS",
			JText::_('VCMBCAHNATION126') => "LR",
			JText::_('VCMBCAHNATION127') => "LY",
			JText::_('VCMBCAHNATION128') => "LI",
			JText::_('VCMBCAHNATION129') => "LT",
			JText::_('VCMBCAHNATION130') => "LU",
			JText::_('VCMBCAHNATION131') => "MO",
			JText::_('VCMBCAHNATION132') => "MK",
			JText::_('VCMBCAHNATION133') => "MG",
			JText::_('VCMBCAHNATION134') => "MW",
			JText::_('VCMBCAHNATION135') => "MY",
			JText::_('VCMBCAHNATION136') => "MV",
			JText::_('VCMBCAHNATION137') => "ML",
			JText::_('VCMBCAHNATION138') => "MT",
			JText::_('VCMBCAHNATION139') => "MH",
			JText::_('VCMBCAHNATION140') => "MQ",
			JText::_('VCMBCAHNATION141') => "MR",
			JText::_('VCMBCAHNATION142') => "MU",
			JText::_('VCMBCAHNATION143') => "YT",
			JText::_('VCMBCAHNATION144') => "MX",
			JText::_('VCMBCAHNATION145') => "FM",
			JText::_('VCMBCAHNATION146') => "MD",
			JText::_('VCMBCAHNATION147') => "MC",
			JText::_('VCMBCAHNATION148') => "MN",
			JText::_('VCMBCAHNATION149') => "ME",
			JText::_('VCMBCAHNATION150') => "MS",
			JText::_('VCMBCAHNATION151') => "MA",
			JText::_('VCMBCAHNATION152') => "MZ",
			JText::_('VCMBCAHNATION153') => "MM",
			JText::_('VCMBCAHNATION154') => "NA",
			JText::_('VCMBCAHNATION155') => "NR",
			JText::_('VCMBCAHNATION156') => "NP",
			JText::_('VCMBCAHNATION157') => "NL",
			JText::_('VCMBCAHNATION158') => "NC",
			JText::_('VCMBCAHNATION159') => "NZ",
			JText::_('VCMBCAHNATION160') => "NI",
			JText::_('VCMBCAHNATION161') => "NE",
			JText::_('VCMBCAHNATION162') => "NG",
			JText::_('VCMBCAHNATION163') => "NU",
			JText::_('VCMBCAHNATION164') => "NF",
			JText::_('VCMBCAHNATION165') => "MP",
			JText::_('VCMBCAHNATION166') => "NO",
			JText::_('VCMBCAHNATION167') => "OM",
			JText::_('VCMBCAHNATION168') => "PK",
			JText::_('VCMBCAHNATION169') => "PW",
			JText::_('VCMBCAHNATION170') => "PS",
			JText::_('VCMBCAHNATION171') => "PA",
			JText::_('VCMBCAHNATION172') => "PG",
			JText::_('VCMBCAHNATION173') => "PY",
			JText::_('VCMBCAHNATION174') => "PE",
			JText::_('VCMBCAHNATION175') => "PH",
			JText::_('VCMBCAHNATION176') => "PN",
			JText::_('VCMBCAHNATION177') => "PL",
			JText::_('VCMBCAHNATION178') => "PT",
			JText::_('VCMBCAHNATION179') => "PR",
			JText::_('VCMBCAHNATION180') => "QA",
			JText::_('VCMBCAHNATION181') => "RE",
			JText::_('VCMBCAHNATION182') => "RO",
			JText::_('VCMBCAHNATION183') => "RU",
			JText::_('VCMBCAHNATION184') => "RW",
			JText::_('VCMBCAHNATION185') => "BL",
			JText::_('VCMBCAHNATION186') => "SH",
			JText::_('VCMBCAHNATION187') => "KN",
			JText::_('VCMBCAHNATION188') => "LC",
			JText::_('VCMBCAHNATION189') => "MF",
			JText::_('VCMBCAHNATION190') => "PM",
			JText::_('VCMBCAHNATION191') => "VC",
			JText::_('VCMBCAHNATION192') => "WS",
			JText::_('VCMBCAHNATION193') => "SM",
			JText::_('VCMBCAHNATION194') => "ST",
			JText::_('VCMBCAHNATION195') => "SA",
			JText::_('VCMBCAHNATION196') => "SN",
			JText::_('VCMBCAHNATION197') => "RS",
			JText::_('VCMBCAHNATION198') => "SC",
			JText::_('VCMBCAHNATION199') => "SL",
			JText::_('VCMBCAHNATION200') => "SG",
			JText::_('VCMBCAHNATION201') => "SX",
			JText::_('VCMBCAHNATION202') => "SK",
			JText::_('VCMBCAHNATION203') => "SI",
			JText::_('VCMBCAHNATION204') => "SB",
			JText::_('VCMBCAHNATION205') => "SO",
			JText::_('VCMBCAHNATION206') => "ZA",
			JText::_('VCMBCAHNATION207') => "GS",
			JText::_('VCMBCAHNATION208') => "SS",
			JText::_('VCMBCAHNATION209') => "ES",
			JText::_('VCMBCAHNATION210') => "LK",
			JText::_('VCMBCAHNATION211') => "SD",
			JText::_('VCMBCAHNATION212') => "SR",
			JText::_('VCMBCAHNATION213') => "SJ",
			JText::_('VCMBCAHNATION214') => "SZ",
			JText::_('VCMBCAHNATION215') => "SE",
			JText::_('VCMBCAHNATION216') => "CH",
			JText::_('VCMBCAHNATION217') => "SY",
			JText::_('VCMBCAHNATION218') => "TW",
			JText::_('VCMBCAHNATION219') => "TJ",
			JText::_('VCMBCAHNATION220') => "TZ",
			JText::_('VCMBCAHNATION223') => "TH",
			JText::_('VCMBCAHNATION224') => "TL",
			JText::_('VCMBCAHNATION225') => "TG",
			JText::_('VCMBCAHNATION226') => "TK",
			JText::_('VCMBCAHNATION227') => "TO",
			JText::_('VCMBCAHNATION228') => "TT",
			JText::_('VCMBCAHNATION229') => "TN",
			JText::_('VCMBCAHNATION230') => "TR",
			JText::_('VCMBCAHNATION231') => "TM",
			JText::_('VCMBCAHNATION232') => "TC",
			JText::_('VCMBCAHNATION233') => "TV",
			JText::_('VCMBCAHNATION234') => "UG",
			JText::_('VCMBCAHNATION235') => "UA",
			JText::_('VCMBCAHNATION236') => "AE",
			JText::_('VCMBCAHNATION237') => "GB",
			JText::_('VCMBCAHNATION238') => "US",
			JText::_('VCMBCAHNATION239') => "UM",
			JText::_('VCMBCAHNATION240') => "UY",
			JText::_('VCMBCAHNATION241') => "UZ",
			JText::_('VCMBCAHNATION242') => "VU",
			JText::_('VCMBCAHNATION243') => "VE",
			JText::_('VCMBCAHNATION244') => "VN",
			JText::_('VCMBCAHNATION245') => "VG",
			JText::_('VCMBCAHNATION246') => "VI",
			JText::_('VCMBCAHNATION247') => "WF",
			JText::_('VCMBCAHNATION248') => "EH",
			JText::_('VCMBCAHNATION249') => "YE",
			JText::_('VCMBCAHNATION250') => "ZM",
			JText::_('VCMBCAHNATION251') => "ZW"
		);

		$policyCodes = array(
			JText::_('VCMBCAHPOLTYPE1') => 1,
			JText::_('VCMBCAHPOLTYPE2') => 12,
			JText::_('VCMBCAHPOLTYPE3') => 14,
			JText::_('VCMBCAHPOLTYPE4') => 15,
			JText::_('VCMBCAHPOLTYPE5') => 16,
			JText::_('VCMBCAHPOLTYPE6') => 29,
			JText::_('VCMBCAHPOLTYPE7') => 30,
			JText::_('VCMBCAHPOLTYPE8') => 31,
			JText::_('VCMBCAHPOLTYPE9') => 33,
			JText::_('VCMBCAHPOLTYPE10') => 34,
			JText::_('VCMBCAHPOLTYPE11') => 36,
			JText::_('VCMBCAHPOLTYPE12') => 37,
			JText::_('VCMBCAHPOLTYPE13') => 38,
			JText::_('VCMBCAHPOLTYPE14') => 41,
			JText::_('VCMBCAHPOLTYPE15') => 42,
			JText::_('VCMBCAHPOLTYPE16') => 43,
			JText::_('VCMBCAHPOLTYPE17') => 44,
			JText::_('VCMBCAHPOLTYPE18') => 45,
			JText::_('VCMBCAHPOLTYPE19') => 46,
			JText::_('VCMBCAHPOLTYPE20') => 47,
			JText::_('VCMBCAHPOLTYPE21') => 48,
			JText::_('VCMBCAHPOLTYPE22') => 49,
			JText::_('VCMBCAHPOLTYPE23') => 50,
			JText::_('VCMBCAHPOLTYPE24') => 51,
			JText::_('VCMBCAHPOLTYPE25') => 52,
			JText::_('VCMBCAHPOLTYPE26') => 53,
			JText::_('VCMBCAHPOLTYPE27') => 54,
			JText::_('VCMBCAHPOLTYPE28') => 55,
			JText::_('VCMBCAHPOLTYPE29') => 56,
			JText::_('VCMBCAHPOLTYPE30') => 57,
			JText::_('VCMBCAHPOLTYPE31') => 58,
			JText::_('VCMBCAHPOLTYPE32') => 59,
			JText::_('VCMBCAHPOLTYPE33') => 60,
			JText::_('VCMBCAHPOLTYPE34') => 61,
			JText::_('VCMBCAHPOLTYPE35') => 62,
			JText::_('VCMBCAHPOLTYPE36') => 63,
			JText::_('VCMBCAHPOLTYPE37') => 64,
			JText::_('VCMBCAHPOLTYPE38') => 65,
			JText::_('VCMBCAHPOLTYPE39') => 66,
			JText::_('VCMBCAHPOLTYPE40') => 67,
			JText::_('VCMBCAHPOLTYPE41') => 68,
			JText::_('VCMBCAHPOLTYPE42') => 69,
			JText::_('VCMBCAHPOLTYPE43') => 70,
			JText::_('VCMBCAHPOLTYPE44') => 71,
			JText::_('VCMBCAHPOLTYPE45') => 72,
			JText::_('VCMBCAHPOLTYPE46') => 73,
			JText::_('VCMBCAHPOLTYPE47') => 74,
			JText::_('VCMBCAHPOLTYPE48') => 113,
			JText::_('VCMBCAHPOLTYPE49') => 114,
			JText::_('VCMBCAHPOLTYPE50') => 115,
			JText::_('VCMBCAHPOLTYPE51') => 116,
			JText::_('VCMBCAHPOLTYPE52') => 117,
			JText::_('VCMBCAHPOLTYPE53') => 118,
			JText::_('VCMBCAHPOLTYPE54') => 119,
			JText::_('VCMBCAHPOLTYPE55') => 120,
			JText::_('VCMBCAHPOLTYPE56') => 121,
			JText::_('VCMBCAHPOLTYPE57') => 2,
			JText::_('VCMBCAHPOLTYPE58') => 4,
			JText::_('VCMBCAHPOLTYPE59') => 5,
			JText::_('VCMBCAHPOLTYPE60') => 6,
			JText::_('VCMBCAHPOLTYPE61') => 7,
			JText::_('VCMBCAHPOLTYPE62') => 9,
			JText::_('VCMBCAHPOLTYPE63') => 10,
			JText::_('VCMBCAHPOLTYPE64') => 11,
			JText::_('VCMBCAHPOLTYPE65') => 75,
			JText::_('VCMBCAHPOLTYPE66') => 76,
			JText::_('VCMBCAHPOLTYPE67') => 77,
			JText::_('VCMBCAHPOLTYPE68') => 78,
			JText::_('VCMBCAHPOLTYPE69') => 79,
			JText::_('VCMBCAHPOLTYPE70') => 80,
			JText::_('VCMBCAHPOLTYPE71') => 81,
			JText::_('VCMBCAHPOLTYPE72') => 82,
			JText::_('VCMBCAHPOLTYPE73') => 83,
			JText::_('VCMBCAHPOLTYPE74') => 84,
			JText::_('VCMBCAHPOLTYPE75') => 85,
			JText::_('VCMBCAHPOLTYPE76') => 86,
			JText::_('VCMBCAHPOLTYPE77') => 87,
			JText::_('VCMBCAHPOLTYPE78') => 88,
			JText::_('VCMBCAHPOLTYPE79') => 89,
			JText::_('VCMBCAHPOLTYPE80') => 90,
			JText::_('VCMBCAHPOLTYPE81') => 91,
			JText::_('VCMBCAHPOLTYPE82') => 92,
			JText::_('VCMBCAHPOLTYPE83') => 93,
			JText::_('VCMBCAHPOLTYPE84') => 94,
			JText::_('VCMBCAHPOLTYPE85') => 95,
			JText::_('VCMBCAHPOLTYPE86') => 96,
			JText::_('VCMBCAHPOLTYPE87') => 97,
			JText::_('VCMBCAHPOLTYPE88') => 98,
			JText::_('VCMBCAHPOLTYPE89') => 99,
			JText::_('VCMBCAHPOLTYPE90') => 100,
			JText::_('VCMBCAHPOLTYPE91') => 101,
			JText::_('VCMBCAHPOLTYPE92') => 102,
			JText::_('VCMBCAHPOLTYPE93') => 122,
			JText::_('VCMBCAHPOLTYPE94') => 123,
			JText::_('VCMBCAHPOLTYPE95') => 124,
			JText::_('VCMBCAHPOLTYPE96') => 125,
			JText::_('VCMBCAHPOLTYPE97') => 126,
			JText::_('VCMBCAHPOLTYPE98') => 127,
			JText::_('VCMBCAHPOLTYPE99') => 128,
			JText::_('VCMBCAHPOLTYPE100') => 129,
			JText::_('VCMBCAHPOLTYPE101') => 130,
			JText::_('VCMBCAHPOLTYPE102') => 131,
			JText::_('VCMBCAHPOLTYPE103') => 132,
			JText::_('VCMBCAHPOLTYPE104') => 133,
			JText::_('VCMBCAHPOLTYPE105') => 134,
			JText::_('VCMBCAHPOLTYPE106') => 135,
			JText::_('VCMBCAHPOLTYPE107') => 136,
			JText::_('VCMBCAHPOLTYPE108') => 137,
			JText::_('VCMBCAHPOLTYPE109') => 138,
			JText::_('VCMBCAHPOLTYPE110') => 139
		);

		$imageTagCodes = array(
			JText::_('VCMBCAHIMGTAG1') => 1,
			JText::_('VCMBCAHIMGTAG2') => 2,
			JText::_('VCMBCAHIMGTAG3') => 3,
			JText::_('VCMBCAHIMGTAG4') => 4,
			JText::_('VCMBCAHIMGTAG5') => 5,
			JText::_('VCMBCAHIMGTAG6') => 6,
			JText::_('VCMBCAHIMGTAG7') => 7,
			JText::_('VCMBCAHIMGTAG8') => 8,
			JText::_('VCMBCAHIMGTAG9') => 10,
			JText::_('VCMBCAHIMGTAG10') => 11,
			JText::_('VCMBCAHIMGTAG11') => 13,
			JText::_('VCMBCAHIMGTAG12') => 14,
			JText::_('VCMBCAHIMGTAG13') => 37,
			JText::_('VCMBCAHIMGTAG14') => 41,
			JText::_('VCMBCAHIMGTAG15') => 42,
			JText::_('VCMBCAHIMGTAG16') => 43,
			JText::_('VCMBCAHIMGTAG17') => 50,
			JText::_('VCMBCAHIMGTAG18') => 55,
			JText::_('VCMBCAHIMGTAG19') => 61,
			JText::_('VCMBCAHIMGTAG20') => 70,
			JText::_('VCMBCAHIMGTAG21') => 74,
			JText::_('VCMBCAHIMGTAG22') => 81,
			JText::_('VCMBCAHIMGTAG23') => 82,
			JText::_('VCMBCAHIMGTAG24') => 87,
			JText::_('VCMBCAHIMGTAG25') => 89,
			JText::_('VCMBCAHIMGTAG26') => 90,
			JText::_('VCMBCAHIMGTAG27') => 94,
			JText::_('VCMBCAHIMGTAG28') => 95,
			JText::_('VCMBCAHIMGTAG29') => 96,
			JText::_('VCMBCAHIMGTAG30') => 97,
			JText::_('VCMBCAHIMGTAG31') => 100,
			JText::_('VCMBCAHIMGTAG32') => 102,
			JText::_('VCMBCAHIMGTAG33') => 103,
			JText::_('VCMBCAHIMGTAG34') => 104,
			JText::_('VCMBCAHIMGTAG35') => 106,
			JText::_('VCMBCAHIMGTAG36') => 107,
			JText::_('VCMBCAHIMGTAG37') => 108,
			JText::_('VCMBCAHIMGTAG38') => 112,
			JText::_('VCMBCAHIMGTAG39') => 113,
			JText::_('VCMBCAHIMGTAG40') => 114,
			JText::_('VCMBCAHIMGTAG41') => 115,
			JText::_('VCMBCAHIMGTAG42') => 116,
			JText::_('VCMBCAHIMGTAG43') => 124,
			JText::_('VCMBCAHIMGTAG44') => 125,
			JText::_('VCMBCAHIMGTAG45') => 128,
			JText::_('VCMBCAHIMGTAG46') => 131,
			JText::_('VCMBCAHIMGTAG47') => 133,
			JText::_('VCMBCAHIMGTAG48') => 134,
			JText::_('VCMBCAHIMGTAG49') => 137,
			JText::_('VCMBCAHIMGTAG50') => 141,
			JText::_('VCMBCAHIMGTAG51') => 143,
			JText::_('VCMBCAHIMGTAG52') => 153,
			JText::_('VCMBCAHIMGTAG53') => 154,
			JText::_('VCMBCAHIMGTAG54') => 155,
			JText::_('VCMBCAHIMGTAG55') => 156,
			JText::_('VCMBCAHIMGTAG56') => 157,
			JText::_('VCMBCAHIMGTAG57') => 158,
			JText::_('VCMBCAHIMGTAG58') => 159,
			JText::_('VCMBCAHIMGTAG59') => 160,
			JText::_('VCMBCAHIMGTAG60') => 161,
			JText::_('VCMBCAHIMGTAG61') => 164,
			JText::_('VCMBCAHIMGTAG62') => 165,
			JText::_('VCMBCAHIMGTAG63') => 167,
			JText::_('VCMBCAHIMGTAG64') => 172,
			JText::_('VCMBCAHIMGTAG65') => 173,
			JText::_('VCMBCAHIMGTAG66') => 177,
			JText::_('VCMBCAHIMGTAG67') => 178,
			JText::_('VCMBCAHIMGTAG68') => 179,
			JText::_('VCMBCAHIMGTAG69') => 182,
			JText::_('VCMBCAHIMGTAG70') => 183,
			JText::_('VCMBCAHIMGTAG71') => 184,
			JText::_('VCMBCAHIMGTAG72') => 185,
			JText::_('VCMBCAHIMGTAG73') => 186,
			JText::_('VCMBCAHIMGTAG74') => 187,
			JText::_('VCMBCAHIMGTAG75') => 188,
			JText::_('VCMBCAHIMGTAG76') => 189,
			JText::_('VCMBCAHIMGTAG77') => 190,
			JText::_('VCMBCAHIMGTAG78') => 191,
			JText::_('VCMBCAHIMGTAG79') => 192,
			JText::_('VCMBCAHIMGTAG80') => 193,
			JText::_('VCMBCAHIMGTAG81') => 194,
			JText::_('VCMBCAHIMGTAG82') => 197,
			JText::_('VCMBCAHIMGTAG83') => 198,
			JText::_('VCMBCAHIMGTAG84') => 199,
			JText::_('VCMBCAHIMGTAG85') => 204,
			JText::_('VCMBCAHIMGTAG86') => 205,
			JText::_('VCMBCAHIMGTAG87') => 240,
			JText::_('VCMBCAHIMGTAG88') => 241,
			JText::_('VCMBCAHIMGTAG89') => 242,
			JText::_('VCMBCAHIMGTAG90') => 245,
			JText::_('VCMBCAHIMGTAG91') => 246,
			JText::_('VCMBCAHIMGTAG92') => 247,
			JText::_('VCMBCAHIMGTAG93') => 248,
			JText::_('VCMBCAHIMGTAG94') => 249,
			JText::_('VCMBCAHIMGTAG95') => 250,
			JText::_('VCMBCAHIMGTAG96') => 251,
			JText::_('VCMBCAHIMGTAG97') => 252,
			JText::_('VCMBCAHIMGTAG98') => 253,
			JText::_('VCMBCAHIMGTAG99') => 254,
			JText::_('VCMBCAHIMGTAG100') => 255,
			JText::_('VCMBCAHIMGTAG101') => 256,
			JText::_('VCMBCAHIMGTAG102') => 257,
			JText::_('VCMBCAHIMGTAG103') => 258,
			JText::_('VCMBCAHIMGTAG104') => 259,
			JText::_('VCMBCAHIMGTAG105') => 260,
			JText::_('VCMBCAHIMGTAG106') => 261,
			JText::_('VCMBCAHIMGTAG107') => 262,
			JText::_('VCMBCAHIMGTAG108') => 263,
			JText::_('VCMBCAHIMGTAG109') => 264,
			JText::_('VCMBCAHIMGTAG110') => 265,
			JText::_('VCMBCAHIMGTAG111') => 266,
			JText::_('VCMBCAHIMGTAG112') => 267,
			JText::_('VCMBCAHIMGTAG113') => 268,
			JText::_('VCMBCAHIMGTAG114') => 269,
			JText::_('VCMBCAHIMGTAG115') => 270,
			JText::_('VCMBCAHIMGTAG116') => 271,
			JText::_('VCMBCAHIMGTAG117') => 272,
			JText::_('VCMBCAHIMGTAG118') => 273,
			JText::_('VCMBCAHIMGTAG119') => 274,
			JText::_('VCMBCAHIMGTAG120') => 275,
			JText::_('VCMBCAHIMGTAG121') => 276,
			JText::_('VCMBCAHIMGTAG122') => 277,
			JText::_('VCMBCAHIMGTAG123') => 278,
			JText::_('VCMBCAHIMGTAG124') => 279,
			JText::_('VCMBCAHIMGTAG125') => 280,
			JText::_('VCMBCAHIMGTAG126') => 281,
			JText::_('VCMBCAHIMGTAG127') => 282,
			JText::_('VCMBCAHIMGTAG128') => 283,
			JText::_('VCMBCAHIMGTAG129') => 284,
			JText::_('VCMBCAHIMGTAG130') => 285,
			JText::_('VCMBCAHIMGTAG131') => 286,
			JText::_('VCMBCAHIMGTAG132') => 287,
			JText::_('VCMBCAHIMGTAG133') => 288,
			JText::_('VCMBCAHIMGTAG134') => 289,
			JText::_('VCMBCAHIMGTAG135') => 290,
			JText::_('VCMBCAHIMGTAG136') => 291
		);

		natcasesort($RMAAmenitiesNames);

		$this->RMAAmenitiesNames = $RMAAmenitiesNames;
		$this->RMAAmenitiesCodes = $RMAAmenitiesCodes;
		$this->languageCodes = $languageCodes;
		$this->countryCodes = $countryCodes;
		$this->policyCodes = $policyCodes;
		$this->imageTagCodes = $imageTagCodes;
		$this->oldData = $oldData;
		$this->hotelName = $hotelName;
		$this->sessionValues = $sessionValues;
		$this->inputTypeReset = $inputTypeReset;

		// Display the template (default.php)
		parent::display($tpl);
		
	}

	/**
	 * Setting the toolbar
	 */
	protected function addToolBar() {
		//Add menu title and some buttons to the page
		JToolBarHelper::title(JText::_('VCMMAINTBCAHCONT'), 'vikchannelmanager');
		JToolBarHelper::cancel( 'cancel', JText::_('CANCEL'));
		JToolBarHelper::custom('bca.readHotelInfo', 'download', 'download', JText::_('VCMBCAHIDOWNLOADDATA'), false);
		JToolBarHelper::spacer();		
	}
}
